services:
  web:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/.htaccess:/var/www/html/.htaccess
  db:
    container_name: php_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=php_db
    ports:
      - '5434:5432'
    volumes:
      - ./db:/var/lib/postgresql/data